### ISSUE TITLE
Build difficulties on CentOS 8

### ISSUE THREAD

**Issue by mike-myers-tob** [trailofbits/ebpfpub#44]
I was able to build `ebpfpub` on CentOS 8 but there were some obstacles. I want to make sure I did this right, and if so, maybe we can update the `README` regarding the needed dependencies.

1. I downloaded the osquery toolchain and gave the path to it, but the configure step fails with:

```
/home/trailofbits/Downloads/osquery-toolchain-1.1.0-x86_64/usr/bin/clang is not a full path to an existing compiler tool.
```

Workaround: build with the system toolchain instead.

2. proceeding to build with the system toolchain, fails with:

```
could not find a package configuration file provided by "LLVM" with any of the following names
```

Solution: `yum install llvm-devel` which installs the missing the `LLVMConfig.cmake` files.

3. Linking errors because llvm-dev is missing a bunch of libraries:

```
/usr/bin/ld: cannot find -lLLVMCore 
/usr/bin/ld: cannot find -lLLVMBPFCodeGen
 /usr/bin/ld: cannot find -lLLVMX86CodeGen 
/usr/bin/ld: cannot find -lLLVMExecutionEngine 
/usr/bin/ld: cannot find -lLLVMMCJIT
```

Solution: `yum install llvm-static` to install the missing libraries.

4. One last linking error: `/usr/bin/ld: cannot find -ltinfo`

Solution: `yum install ncurses-devel` (installs the `libtinfo` library dependency)

**Comment by alessandrogario** [comment]
The toolchain should take care of the LLVM dependencies if configured liked this:

```
cmake -G Ninja -DEBPF_COMMON_TOOLCHAIN_PATH:PATH=/opt/osquery-toolchain \
  -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DEBPFPUB_ENABLE_INSTALL:BOOL=true \
  -DEBPFPUB_BUILD_EXAMPLES:BOOL=true -DEBPF_COMMON_ENABLE_TESTS:BOOL=true \
  -DEBPF_COMMON_ENABLE_SANITIZERS:BOOL=false ..
```

The CI is using a similar command line here: https://github.com/trailofbits/ebpfpub/blob/master/.github/workflows/main.yml#L91

**Comment by mike-myers-tob** [comment]
Ok, placing the osquery toolchain in `/opt` seems to have fixed the problem in `1.` in my post above. I'll make a PR to update the README with this tip and also building with the system toolchain.

**Comment by alessandrogario** [comment]
> Ok, placing the osquery toolchain in `/opt` seems to have fixed the problem in `1.` in my post above. I'll make a PR to update the README with this tip and also building with the system toolchain.

I think you can move the toolchain to other directories, the key part is not to attempt to pass -DCMAKE_C_COMPILER/-DCMAKE_CXX_COMPILER when using osquery-toolchain because it's automatically handled by the project

**Comment by mike-myers-tob** [comment]
> > Ok, placing the osquery toolchain in `/opt` seems to have fixed the problem in `1.` in my post above. I'll make a PR to update the README with this tip and also building with the system toolchain.
> 
> I think you can move the toolchain to other directories, the key part is not to attempt to pass -DCMAKE_C_COMPILER/-DCMAKE_CXX_COMPILER when using osquery-toolchain because it's automatically handled by the project

I thought I could, but, on two different systems I got those CMake errors about the path to Clang. I think it might have been caused by extracting the archive using the graphical tool (not preserving the top directory name, or something).
