### ISSUE TITLE
Unused or missing CMake variable EBPFPUB_ENABLE_EXAMPLES

### ISSUE THREAD

**Issue by mike-myers-tob** [trailofbits/ebpfpub#47]
The `README` instructions to build include the CMake argument `-DEBPFPUB_ENABLE_EXAMPLES:BOOL=true`.

But it looks like that variable changed or was cut? The configure step will output:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    EBPFPUB_ENABLE_EXAMPLES
```

**Comment by alessandrogario** [comment]
It looks like this option was renamed to `EBPFPUB_BUILD_EXAMPLES`, and I forgot to update the documentation
